// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TODOLAB.Data;

namespace TODOLAB.Migrations.UserToDoDb
{
    [DbContext(typeof(UserToDoDbContext))]
    [Migration("20200610030608_addingConcurrencyStamp")]
    partial class addingConcurrencyStamp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "admin",
                            ConcurrencyStamp = "08bb4973-5be0-4567-8900-b5be9ffe2caa",
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = "moderator",
                            ConcurrencyStamp = "8698dfd2-519e-41b0-8a90-20585fb82d94",
                            Name = "Moderator"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
